export const ErrorCode = {
  UNAUTHORIZED: 'FORBIDDEN',
  SERVER_ERROR: 'SERVER_ERROR',
  REQUEST_FAILED: 'REQUEST_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  NOT_AVAILABLE: 'SERVICE_UNAVAILABLE',
};
